export type Arcana = "Major" | "Minor";
export type Suit = "Cups" | "Wands" | "Swords" | "Pentacles" | null;
export type Element = "Fire" | "Water" | "Air" | "Earth" | "Spirit";

export interface TarotCard {
  id: number;
  name: string;
  arcana: Arcana;
  suit: Suit;
  element: Element;
  uprightMeaning: string;
  reversedMeaning: string;
  symbolism: string;
  imageUrl: string;
  keywords: string[];
}

export interface Spread {
  id: number;
  name: string;
  description: string;
  numberOfCards: number;
  positions: string[];
}

export interface JournalCard {
  id: number;
  tarotCardId: number;
  position: string;
  isReversed: boolean;
  note: string;
}

export interface JournalEntry {
  id: number;
  userId: number;
  spreadId: number;
  title: string;
  question: string;
  interpretation: string;
  cards: JournalCard[];
  createdAt: string;
  updatedAt: string;
}

export interface FavoriteCard {
  id: number;
  userId: number;
  tarotCardId: number;
  createdAt: string;
}

export interface User {
  id: number;
  name: string;
  email: string;
  createdAt: string;
}

export const MOCK_CARDS: TarotCard[] = [
  { id: 1, name: "The Fool", arcana: "Major", suit: null, element: "Air", uprightMeaning: "A new beginning invites you to move forward with curiosity, trust, and an open heart. The Fool encourages a leap of faith even when the entire path is not yet visible.", reversedMeaning: "Impulsiveness, poor judgment, or fear of taking the first step may be blocking progress. Consider the risks without allowing caution to become paralysis.", symbolism: "The cliff represents the unknown, the white rose symbolizes innocence, and the small bag carries lessons from the past without unnecessary weight.", imageUrl: "", keywords: ["beginnings", "freedom", "spontaneity", "faith"] },
  { id: 2, name: "The Magician", arcana: "Major", suit: null, element: "Air", uprightMeaning: "You have the skills, resources, and focus needed to turn an intention into reality. Direct your energy with clarity and take purposeful action.", reversedMeaning: "Your abilities may be unfocused, underused, or directed toward manipulation. Reconnect with your true intention before trying to influence the outcome.", symbolism: "The four suit tools represent complete resources, while one hand points above and the other below to unite idea and action.", imageUrl: "", keywords: ["manifestation", "willpower", "skill", "action"] },
  { id: 3, name: "The High Priestess", arcana: "Major", suit: null, element: "Water", uprightMeaning: "Quiet observation and intuition reveal more than immediate action. Trust the knowledge beneath the surface and allow mystery to unfold in its own time.", reversedMeaning: "You may be ignoring your intuition, withholding important truth, or becoming overwhelmed by hidden emotions. Create enough silence to hear your inner voice again.", symbolism: "The black and white pillars represent duality, the veil guards hidden knowledge, and the moon reflects the cycles of intuition.", imageUrl: "", keywords: ["intuition", "mystery", "stillness", "inner knowledge"] },
  { id: 4, name: "The Empress", arcana: "Major", suit: null, element: "Earth", uprightMeaning: "Creativity, pleasure, and abundance grow when they are given patient care. Nurture your body, your relationships, and the ideas you want to bring into the world.", reversedMeaning: "Creative blocks, overgiving, or dependence on external validation may be draining you. Restore your own needs before continuing to nurture others.", symbolism: "The wheat and lush landscape express fertility, while the starry crown connects earthly creation with a larger natural rhythm.", imageUrl: "", keywords: ["abundance", "creativity", "nurturing", "sensuality"] },
  { id: 5, name: "The Emperor", arcana: "Major", suit: null, element: "Fire", uprightMeaning: "Structure, responsibility, and clear boundaries create stability. Lead with discipline and use authority to protect what you are building.", reversedMeaning: "Control may have become rigidity, domination, or resistance to vulnerability. Reconsider whether your rules support the situation or merely restrict it.", symbolism: "The stone throne represents lasting authority, the mountains show endurance, and the armor suggests readiness to protect and command.", imageUrl: "", keywords: ["authority", "structure", "leadership", "stability"] },
  { id: 6, name: "The Hierophant", arcana: "Major", suit: null, element: "Earth", uprightMeaning: "Tradition, shared values, or an experienced teacher can offer useful guidance. This card favors learning within an established system or community.", reversedMeaning: "Inherited rules may no longer reflect your truth. Question convention thoughtfully and decide which teachings deserve to remain part of your path.", symbolism: "The crossed keys represent access to sacred knowledge, while the two students show wisdom being preserved and passed forward.", imageUrl: "", keywords: ["tradition", "teaching", "belief", "community"] },
  { id: 7, name: "The Lovers", arcana: "Major", suit: null, element: "Air", uprightMeaning: "Connection becomes meaningful through honesty, shared values, and conscious choice. This card may describe love, but it also asks you to choose in alignment with who you truly are.", reversedMeaning: "Disharmony, conflicting values, or avoidance of a necessary choice may be weakening a bond. Restore honesty within yourself before seeking agreement with another person.", symbolism: "The two figures represent vulnerable union, while the angel above them suggests a relationship guided by truth and higher values.", imageUrl: "", keywords: ["love", "alignment", "choice", "union"] },
  { id: 8, name: "The Chariot", arcana: "Major", suit: null, element: "Water", uprightMeaning: "Determination and emotional control can carry you through competing pressures. Choose a direction, hold the reins firmly, and move with confidence.", reversedMeaning: "Scattered motivation, aggression, or a lack of direction may be pulling you off course. Regain control by deciding what deserves your energy.", symbolism: "The opposing sphinxes represent conflicting forces, while the armored charioteer shows the focus required to guide them together.", imageUrl: "", keywords: ["determination", "victory", "direction", "self-control"] },
  { id: 9, name: "Strength", arcana: "Major", suit: null, element: "Fire", uprightMeaning: "True strength appears through patience, compassion, and steady self-command. Meet intensity without suppressing it and guide it with courage.", reversedMeaning: "Self-doubt, insecurity, or poorly managed emotion may be weakening your confidence. Gentleness toward yourself is the beginning of restored power.", symbolism: "The woman calming the lion represents conscious compassion guiding instinct, and the infinity symbol suggests enduring inner power.", imageUrl: "", keywords: ["courage", "compassion", "patience", "inner power"] },
  { id: 10, name: "The Hermit", arcana: "Major", suit: null, element: "Earth", uprightMeaning: "Solitude offers the clarity that noise cannot provide. Step back, reflect carefully, and follow the wisdom discovered through direct experience.", reversedMeaning: "Healthy reflection may have turned into isolation, avoidance, or disconnection. Consider whether you need more time alone or a safe way back toward others.", symbolism: "The lantern illuminates only the next steps, while the mountaintop represents wisdom gained through a demanding personal journey.", imageUrl: "", keywords: ["introspection", "solitude", "wisdom", "guidance"] },
  { id: 11, name: "Wheel of Fortune", arcana: "Major", suit: null, element: "Fire", uprightMeaning: "Circumstances are shifting, opening a new phase in a larger cycle. Work with the movement of change and recognize the opportunities it brings.", reversedMeaning: "Resistance, delays, or repeated patterns may make events feel beyond your control. Focus on your response and on the lesson the cycle continues to present.", symbolism: "The turning wheel reflects changing fortune, while the surrounding figures represent forces of time, knowledge, and destiny.", imageUrl: "", keywords: ["cycles", "change", "destiny", "turning point"] },
  { id: 12, name: "Justice", arcana: "Major", suit: null, element: "Air", uprightMeaning: "Truth, accountability, and balanced judgment are required. Make decisions based on clear evidence and accept the consequences of previous choices.", reversedMeaning: "Bias, denial, or unwillingness to take responsibility may be distorting the situation. Correct what you can and examine where honesty has been avoided.", symbolism: "The scales weigh every factor, the upright sword represents clear judgment, and the throne reflects impartial authority.", imageUrl: "", keywords: ["truth", "fairness", "accountability", "consequences"] },
  { id: 13, name: "The Hanged Man", arcana: "Major", suit: null, element: "Water", uprightMeaning: "Progress comes through pause, surrender, and a different perspective. Release the need to force an answer and allow the situation to reveal itself differently.", reversedMeaning: "The pause may have become unnecessary delay, avoidance, or sacrifice without purpose. Decide whether you are truly surrendering or simply refusing to move.", symbolism: "The reversed position changes perception, the halo shows insight, and the calm expression suggests willing rather than imposed surrender.", imageUrl: "", keywords: ["surrender", "pause", "perspective", "release"] },
  { id: 14, name: "Death", arcana: "Major", suit: null, element: "Water", uprightMeaning: "A chapter has reached its natural ending so that genuine transformation can begin. Release what has expired instead of carrying it into the next phase.", reversedMeaning: "Fear of loss or attachment to the familiar may be prolonging an ending. Change becomes heavier when you continue negotiating with what is already complete.", symbolism: "The skeletal rider represents unavoidable change, while the rising sun beyond the towers promises renewal after an ending.", imageUrl: "", keywords: ["ending", "transformation", "release", "renewal"] },
  { id: 15, name: "Temperance", arcana: "Major", suit: null, element: "Fire", uprightMeaning: "Balance develops through patience, moderation, and thoughtful integration. Combine different needs or influences until they support rather than compete with one another.", reversedMeaning: "Excess, impatience, or conflicting priorities may be creating instability. Slow down and restore proportion before trying to advance.", symbolism: "Water moving between two cups represents careful integration, while one foot on land and one in water unite practical and emotional experience.", imageUrl: "", keywords: ["balance", "moderation", "harmony", "integration"] },
  { id: 16, name: "The Devil", arcana: "Major", suit: null, element: "Earth", uprightMeaning: "Attachment, temptation, or an unhealthy pattern may be limiting your freedom. Recognizing the pattern clearly is the first step toward choosing differently.", reversedMeaning: "Awareness is creating an opportunity to loosen old bonds and reclaim personal power. Release requires responsibility as well as the willingness to change familiar behavior.", symbolism: "The loose chains show that bondage is partly maintained by belief, while the inverted torch points to desire without conscious direction.", imageUrl: "", keywords: ["attachment", "temptation", "shadow", "restriction"] },
  { id: 17, name: "The Tower", arcana: "Major", suit: null, element: "Fire", uprightMeaning: "A sudden truth or disruption breaks apart a structure that could no longer hold. Although unsettling, the collapse creates space for something more honest.", reversedMeaning: "You may be resisting an inevitable change or processing a private upheaval. Avoiding the truth may reduce immediate discomfort while extending the instability.", symbolism: "Lightning represents revelation, the falling crown shows false authority collapsing, and the figures leave a structure built on an unstable foundation.", imageUrl: "", keywords: ["upheaval", "revelation", "collapse", "liberation"] },
  { id: 18, name: "The Star", arcana: "Major", suit: null, element: "Air", uprightMeaning: "Hope returns through healing, openness, and renewed trust in the future. Let yourself be guided by what feels honest, restorative, and quietly meaningful.", reversedMeaning: "Discouragement or disconnection may make possibility difficult to see. Rebuild faith through small acts of care rather than waiting to feel completely certain.", symbolism: "The central star offers guidance, the smaller stars suggest harmony, and the flowing water renews both inner and outer life.", imageUrl: "", keywords: ["hope", "healing", "inspiration", "renewal"] },
  { id: 19, name: "The Moon", arcana: "Major", suit: null, element: "Water", uprightMeaning: "Uncertainty, dreams, and unconscious emotion are shaping perception. Move slowly, listen to intuition, and avoid treating every fear as a fact.", reversedMeaning: "Confusion may be lifting, or hidden anxiety may be becoming impossible to ignore. Name what is real and separate intuition from projection.", symbolism: "The moon illuminates indirectly, the path crosses uncertain terrain, and the dog and wolf represent the tamed and wild sides of instinct.", imageUrl: "", keywords: ["intuition", "illusion", "dreams", "uncertainty"] },
  { id: 20, name: "The Sun", arcana: "Major", suit: null, element: "Fire", uprightMeaning: "Clarity, vitality, and genuine joy are available. Allow yourself to be visible, celebrate progress, and approach life with renewed confidence.", reversedMeaning: "Happiness may feel delayed, diminished, or blocked by unrealistic expectations. The light is still present, but you may need to recognize it in a simpler form.", symbolism: "The radiant sun represents truth and life, the child expresses openness, and the sunflowers turn naturally toward growth.", imageUrl: "", keywords: ["joy", "clarity", "success", "vitality"] },
  { id: 21, name: "Judgement", arcana: "Major", suit: null, element: "Fire", uprightMeaning: "An honest review of the past creates awakening and a chance to respond differently. Answer the call to become more aligned with what you now understand.", reversedMeaning: "Self-doubt, harsh judgment, or refusal to learn from the past may be delaying renewal. Forgiveness does not erase responsibility; it allows movement beyond it.", symbolism: "The trumpet announces awakening, while the rising figures represent consciousness responding to a higher and unavoidable call.", imageUrl: "", keywords: ["awakening", "reflection", "calling", "rebirth"] },
  { id: 22, name: "The World", arcana: "Major", suit: null, element: "Earth", uprightMeaning: "A cycle reaches completion through integration, achievement, and a sense of wholeness. Recognize what you have learned before stepping into the next journey.", reversedMeaning: "Closure may be delayed by unfinished work, shortcuts, or difficulty acknowledging an ending. Identify the final action needed to complete the cycle.", symbolism: "The wreath forms a complete circle, the dancer unites movement and balance, and the four figures represent the elements in harmony.", imageUrl: "", keywords: ["completion", "integration", "achievement", "wholeness"] },
  { id: 23, name: "Ace of Cups", arcana: "Minor", suit: "Cups", element: "Water", uprightMeaning: "A new emotional experience is ready to be received. Open yourself to love, compassion, creativity, or a deeper connection with your own feelings.", reversedMeaning: "Emotions may be blocked, suppressed, or poured into situations that cannot hold them. Refill your own cup before seeking emotional fulfillment elsewhere.", symbolism: "The overflowing chalice represents abundant feeling, the five streams suggest the senses, and the dove brings spiritual openness into emotional life.", imageUrl: "", keywords: ["love", "emotional renewal", "compassion", "openness"] },
  { id: 24, name: "Two of Cups", arcana: "Minor", suit: "Cups", element: "Water", uprightMeaning: "Mutual respect and emotional exchange create a balanced partnership. This may describe romance, friendship, reconciliation, or any bond built through equal participation.", reversedMeaning: "Miscommunication, unequal effort, or conflicting emotional needs may be disrupting a connection. Honest conversation is necessary before harmony can return.", symbolism: "The exchanged cups represent mutual feeling, while the caduceus and lion suggest healing, attraction, and the transformative power of union.", imageUrl: "", keywords: ["partnership", "mutual attraction", "connection", "harmony"] },
  { id: 25, name: "Three of Cups", arcana: "Minor", suit: "Cups", element: "Water", uprightMeaning: "Shared joy, friendship, and community bring emotional renewal. Celebrate progress and allow supportive relationships to strengthen the moment.", reversedMeaning: "Social tension, exclusion, gossip, or excess may be affecting the group. It may also be time to step back and restore your individual emotional balance.", symbolism: "The three raised cups form a circle of shared celebration, while the harvest at their feet represents abundance created through community.", imageUrl: "", keywords: ["celebration", "friendship", "community", "joy"] },
  { id: 26, name: "Four of Cups", arcana: "Minor", suit: "Cups", element: "Water", uprightMeaning: "Emotional withdrawal or dissatisfaction may be making available opportunities difficult to recognize. Pause honestly, but remain open to what is being offered.", reversedMeaning: "Interest and motivation may be returning after a period of emotional stagnation. You are becoming ready to reconnect with life and consider new possibilities.", symbolism: "The three cups represent familiar experience, while the cup offered from a cloud symbolizes an opportunity hidden by inward focus.", imageUrl: "", keywords: ["contemplation", "apathy", "reevaluation", "disconnection"] },
  { id: 27, name: "Five of Cups", arcana: "Minor", suit: "Cups", element: "Water", uprightMeaning: "Loss or disappointment deserves to be acknowledged, but it is not the entire story. Grieve what has spilled while remembering that support and possibility still remain.", reversedMeaning: "Acceptance is beginning to loosen the hold of regret. Forgiveness, emotional recovery, and a willingness to face forward are becoming possible.", symbolism: "The spilled cups represent visible loss, the two upright cups show what remains, and the bridge offers a path back toward safety.", imageUrl: "", keywords: ["grief", "loss", "regret", "acceptance"] },
  { id: 28, name: "Six of Cups", arcana: "Minor", suit: "Cups", element: "Water", uprightMeaning: "Memory, kindness, and familiar connection bring comfort. The past may offer healing or insight, provided it is remembered honestly rather than idealized.", reversedMeaning: "Attachment to the past may be preventing present growth, or old memories may need to be understood differently. Carry the lesson forward without trying to recreate what has ended.", symbolism: "The exchanged flower-filled cup represents innocent generosity, while the familiar village evokes memory, safety, and earlier emotional patterns.", imageUrl: "", keywords: ["nostalgia", "kindness", "memories", "innocence"] },
  { id: 29, name: "Seven of Cups", arcana: "Minor", suit: "Cups", element: "Water", uprightMeaning: "Many possibilities compete for your attention, but not every option is realistic or beneficial. Clarify what you truly value before choosing.", reversedMeaning: "Confusion is beginning to clear, allowing a more grounded decision. Alternatively, fear of choosing may still be keeping you trapped among imagined outcomes.", symbolism: "The seven floating cups contain gifts and dangers, representing fantasy, temptation, projection, and the different forms desire can take.", imageUrl: "", keywords: ["choices", "fantasy", "illusion", "possibility"] },
  { id: 30, name: "Eight of Cups", arcana: "Minor", suit: "Cups", element: "Water", uprightMeaning: "Something once meaningful no longer provides the emotional truth you need. Leaving may be difficult, but the deeper journey requires moving beyond familiar disappointment.", reversedMeaning: "Fear of change may be keeping you in an unfulfilling situation, or you may be reconsidering a departure. Make sure returning is based on renewed truth rather than discomfort with uncertainty.", symbolism: "The abandoned cups show emotional investment left behind, while the mountain path and eclipsed moon mark a difficult search for deeper meaning.", imageUrl: "", keywords: ["departure", "searching", "letting go", "disillusionment"] },
  { id: 31, name: "Nine of Cups", arcana: "Minor", suit: "Cups", element: "Water", uprightMeaning: "Satisfaction, pleasure, and emotional reward are available. Appreciate what has been achieved and allow yourself to enjoy it without apology.", reversedMeaning: "An outward success may not be creating genuine fulfillment, or pleasure may have become excess. Reconsider what emotional satisfaction truly means to you.", symbolism: "The arranged cups display earned abundance, while the seated figure expresses confidence, enjoyment, and pride in personal fulfillment.", imageUrl: "", keywords: ["satisfaction", "pleasure", "gratitude", "wish fulfilled"] },
  { id: 32, name: "Ten of Cups", arcana: "Minor", suit: "Cups", element: "Water", uprightMeaning: "Emotional harmony grows through shared love, belonging, and aligned values. This card supports lasting connection and gratitude for the life created together.", reversedMeaning: "Unspoken conflict, unrealistic expectations, or differences in values may be disturbing harmony. A perfect appearance cannot replace honest emotional connection.", symbolism: "The rainbow of cups represents emotional blessing, while the family and home express belonging, shared joy, and long-term fulfillment.", imageUrl: "", keywords: ["harmony", "family", "belonging", "emotional fulfillment"] },
  { id: 33, name: "Page of Cups", arcana: "Minor", suit: "Cups", element: "Water", uprightMeaning: "A gentle emotional message, creative idea, or intuitive insight is beginning to emerge. Approach it with curiosity and allow yourself to be surprised.", reversedMeaning: "Emotional immaturity, insecurity, or blocked creativity may make feelings difficult to express. Listen inwardly before reacting or seeking reassurance.", symbolism: "The fish rising unexpectedly from the cup represents intuition, imagination, and a message arriving from the unconscious.", imageUrl: "", keywords: ["curiosity", "intuition", "creative message", "sensitivity"] },
  { id: 34, name: "Knight of Cups", arcana: "Minor", suit: "Cups", element: "Water", uprightMeaning: "Follow the heart with imagination, charm, and sincere emotional intention. An invitation, romantic gesture, or creative pursuit may be moving toward you.", reversedMeaning: "Idealization, moodiness, or promises unsupported by action may create disappointment. Distinguish genuine sensitivity from emotional performance or escapism.", symbolism: "The knight carries the cup carefully rather than as a weapon, while the calm horse reflects graceful movement guided by feeling.", imageUrl: "", keywords: ["romance", "invitation", "idealism", "following the heart"] },
  { id: 35, name: "Queen of Cups", arcana: "Minor", suit: "Cups", element: "Water", uprightMeaning: "Emotional intelligence and intuitive understanding allow you to hold space without losing yourself. Lead with compassion while honoring healthy boundaries.", reversedMeaning: "Emotional overwhelm, insecurity, or overinvolvement in another person's feelings may be draining you. Turn your care inward and restore clear boundaries.", symbolism: "The queen's ornate closed cup represents deep inner feeling, while the water at her feet connects her with intuition and the unconscious.", imageUrl: "", keywords: ["compassion", "intuition", "empathy", "emotional maturity"] },
  { id: 36, name: "King of Cups", arcana: "Minor", suit: "Cups", element: "Water", uprightMeaning: "Emotional steadiness allows compassion and reason to work together. Respond with maturity, remain calm under pressure, and guide feeling without suppressing it.", reversedMeaning: "Emotional control may have become manipulation, withdrawal, or volatility beneath a composed surface. Take responsibility for feelings before using them to influence others.", symbolism: "The king's throne remains stable upon turbulent water, showing emotional mastery even while powerful feelings move around him.", imageUrl: "", keywords: ["emotional balance", "wisdom", "diplomacy", "calm"] },
  { id: 37, name: "Ace of Wands", arcana: "Minor", suit: "Wands", element: "Fire", uprightMeaning: "A powerful spark of inspiration invites action, creativity, and growth. Follow the idea that makes you feel more alive and give it room to develop.", reversedMeaning: "Delays, low motivation, or uncertainty may be preventing an idea from taking shape. Reconnect with the original desire before forcing yourself to move.", symbolism: "The hand offering a budding wand represents raw potential, while the distant castle suggests the future that inspired action can build.", imageUrl: "", keywords: ["inspiration", "potential", "creative spark", "initiative"] },
  { id: 38, name: "Two of Wands", arcana: "Minor", suit: "Wands", element: "Fire", uprightMeaning: "A wider future is becoming visible, and careful planning can turn ambition into direction. Consider your options before leaving what is familiar.", reversedMeaning: "Fear of uncertainty, limited planning, or attachment to comfort may be shrinking your possibilities. Clarify the risk instead of allowing it to make the decision for you.", symbolism: "The globe represents possibility and personal power, while the figure between two wands stands between security and expansion.", imageUrl: "", keywords: ["planning", "possibility", "ambition", "future vision"] },
  { id: 39, name: "Three of Wands", arcana: "Minor", suit: "Wands", element: "Fire", uprightMeaning: "Previous effort is beginning to open new opportunities. Look beyond the immediate horizon, expand your plans, and prepare to work with what returns.", reversedMeaning: "Delays, poor coordination, or expectations disconnected from reality may be limiting progress. Reassess the plan and the support required to move farther.", symbolism: "The ships represent ventures in motion, while the elevated viewpoint allows the figure to watch effort travel into a larger world.", imageUrl: "", keywords: ["expansion", "foresight", "progress", "opportunity"] },
  { id: 40, name: "Four of Wands", arcana: "Minor", suit: "Wands", element: "Fire", uprightMeaning: "A stable milestone deserves recognition and celebration. Community, home, or shared achievement creates a strong foundation for what comes next.", reversedMeaning: "Celebration may be private, delayed, or disturbed by tension at home or within a group. Define what belonging and stability mean for you personally.", symbolism: "The flowered garland joins four upright wands into a welcoming threshold, while the figures and castle suggest community and security.", imageUrl: "", keywords: ["celebration", "homecoming", "community", "stability"] },
  { id: 41, name: "Five of Wands", arcana: "Minor", suit: "Wands", element: "Fire", uprightMeaning: "Different ambitions, opinions, or working styles are creating friction. Healthy competition can sharpen your abilities if conflict remains constructive.", reversedMeaning: "Conflict may be avoided, resolved, or quietly continuing beneath the surface. Choose cooperation where possible, but do not confuse silence with genuine agreement.", symbolism: "The crossing wands and mismatched clothing show competing perspectives, energy without coordination, and a struggle that has not become true battle.", imageUrl: "", keywords: ["competition", "conflict", "tension", "diverse perspectives"] },
  { id: 42, name: "Six of Wands", arcana: "Minor", suit: "Wands", element: "Fire", uprightMeaning: "Effort receives recognition, support, or visible success. Accept the achievement with confidence while remembering the people and discipline that helped create it.", reversedMeaning: "Recognition may be delayed, confidence may depend too heavily on approval, or success may feel less satisfying than expected. Measure progress by values as well as applause.", symbolism: "The laurel wreath represents victory, while the rider's elevated position and surrounding crowd show public recognition and collective support.", imageUrl: "", keywords: ["victory", "recognition", "confidence", "progress"] },
  { id: 43, name: "Seven of Wands", arcana: "Minor", suit: "Wands", element: "Fire", uprightMeaning: "Your position is being challenged, and maintaining it requires courage and persistence. Protect what matters without wasting energy on every disagreement.", reversedMeaning: "Pressure, exhaustion, or self-doubt may be weakening your boundaries. Decide which battles are necessary and where stepping back would preserve strength.", symbolism: "The figure stands on higher ground against six rising wands, representing advantage, defense, and the effort required to hold a position.", imageUrl: "", keywords: ["defense", "conviction", "perseverance", "boundaries"] },
  { id: 44, name: "Eight of Wands", arcana: "Minor", suit: "Wands", element: "Fire", uprightMeaning: "Events accelerate and communication moves quickly. Use the momentum, respond clearly, and allow focused action to carry the situation forward.", reversedMeaning: "Delays, mixed messages, or scattered urgency may create frustration. Slow the process enough to correct direction before increasing speed again.", symbolism: "The eight flying wands cross an open sky without obstruction, representing swift movement, direct energy, and events already in motion.", imageUrl: "", keywords: ["momentum", "speed", "communication", "movement"] },
  { id: 45, name: "Nine of Wands", arcana: "Minor", suit: "Wands", element: "Fire", uprightMeaning: "You are tired but experienced, and the boundary protecting your progress still matters. Remain alert, use what previous challenges taught you, and continue carefully.", reversedMeaning: "Exhaustion, defensiveness, or repeated struggle may be reaching an unsustainable point. Rest, ask for support, and examine whether every barrier still needs to remain.", symbolism: "The bandaged figure shows resilience after conflict, while the wall of wands forms both protection and evidence of accumulated vigilance.", imageUrl: "", keywords: ["resilience", "persistence", "boundaries", "caution"] },
  { id: 46, name: "Ten of Wands", arcana: "Minor", suit: "Wands", element: "Fire", uprightMeaning: "Responsibility has grown into a heavy burden, even if the destination is close. Complete what matters, but delegate or release what does not need to be carried alone.", reversedMeaning: "The weight may finally be released, or overwhelm may be preventing effective action. Admit your limits before exhaustion chooses them for you.", symbolism: "The ten bundled wands block the figure's view, showing how accumulated duties can obscure direction even while progress continues.", imageUrl: "", keywords: ["burden", "responsibility", "overwork", "completion"] },
  { id: 47, name: "Page of Wands", arcana: "Minor", suit: "Wands", element: "Fire", uprightMeaning: "Curiosity and enthusiasm invite exploration. A new idea, message, or direction may not be fully developed, but it is ready to be tested through experience.", reversedMeaning: "Restlessness, insecurity, or inconsistent effort may keep inspiration from developing. Give the idea a simple structure instead of chasing every new spark.", symbolism: "The page studies the budding wand with fascination, while the open desert suggests potential that depends on initiative and imagination.", imageUrl: "", keywords: ["exploration", "enthusiasm", "discovery", "new idea"] },
  { id: 48, name: "Knight of Wands", arcana: "Minor", suit: "Wands", element: "Fire", uprightMeaning: "Bold movement, passion, and adventure push the situation forward. Act courageously, but give powerful enthusiasm enough direction to become productive.", reversedMeaning: "Impulsiveness, frustration, or inconsistent commitment may create unnecessary disruption. Speed without preparation can turn confidence into recklessness.", symbolism: "The rearing horse and flame-patterned clothing express intense motion, courage, and a desire to pursue experience without hesitation.", imageUrl: "", keywords: ["adventure", "passion", "bold action", "momentum"] },
  { id: 49, name: "Queen of Wands", arcana: "Minor", suit: "Wands", element: "Fire", uprightMeaning: "Confidence, warmth, and creative independence make your presence influential. Trust your abilities and encourage others without making yourself smaller.", reversedMeaning: "Jealousy, insecurity, or a need for attention may be distorting natural confidence. Reconnect with your own value instead of comparing your light with someone else's.", symbolism: "The sunflower mirrors radiant self-expression, while the black cat suggests intuition, independence, and comfort with personal power.", imageUrl: "", keywords: ["confidence", "charisma", "independence", "creativity"] },
  { id: 50, name: "King of Wands", arcana: "Minor", suit: "Wands", element: "Fire", uprightMeaning: "Vision becomes leadership when supported by courage and consistent action. Inspire others, think beyond immediate limits, and take responsibility for the direction you set.", reversedMeaning: "Arrogance, impatience, or unrealistic expectations may turn leadership into domination. Temper ambition with listening, planning, and accountability.", symbolism: "The flowering wand shows sustained creative life, while the salamanders represent fire mastered through experience rather than uncontrolled impulse.", imageUrl: "", keywords: ["leadership", "vision", "enterprise", "confidence"] },
  { id: 53, name: "Three of Swords", arcana: "Minor", suit: "Swords", element: "Air", uprightMeaning: "Heartbreak, sorrow, painful truths.", reversedMeaning: "Recovery, forgiveness, releasing pain.", symbolism: "A heart pierced by three blades in a stormy sky.", imageUrl: "", keywords: ["sorrow", "release"] },
  { id: 65, name: "Ace of Pentacles", arcana: "Minor", suit: "Pentacles", element: "Earth", uprightMeaning: "New financial opportunity, prosperity, manifestation.", reversedMeaning: "Missed opportunity, scarcity mindset.", symbolism: "A golden coin blooms from an open palm.", imageUrl: "", keywords: ["prosperity", "opportunity"] },
  { id: 77, name: "Queen of Pentacles", arcana: "Minor", suit: "Pentacles", element: "Earth", uprightMeaning: "Practical, nurturing, financial security.", reversedMeaning: "Self-care neglected, imbalance.", symbolism: "A queen enthroned in a lush garden.", imageUrl: "", keywords: ["nurture", "abundance"] },
];

export const MOCK_SPREADS: Spread[] = [
  { id: 1, name: "Single Card", description: "A simple daily draw for guidance.", numberOfCards: 1, positions: ["Message"] },
  { id: 2, name: "Past · Present · Future", description: "A three-card reading tracing your timeline.", numberOfCards: 3, positions: ["Past", "Present", "Future"] },
  { id: 3, name: "Mind · Body · Spirit", description: "A holistic look at your current state.", numberOfCards: 3, positions: ["Mind", "Body", "Spirit"] },
  { id: 4, name: "Celtic Cross", description: "A deep ten-card spread for complex questions.", numberOfCards: 10, positions: ["Present", "Challenge", "Past", "Future", "Above", "Below", "Advice", "External", "Hopes", "Outcome"] },
  { id: 5, name: "Relationship Spread", description: "Insight into a bond between two souls.", numberOfCards: 5, positions: ["You", "Them", "Connection", "Challenge", "Potential"] },
];

export const MOCK_USER: User = {
  id: 1,
  name: "Victoria",
  email: "victoria@email.com",
  createdAt: "2026-01-14",
};

export const MOCK_READINGS: JournalEntry[] = [
  {
    id: 25,
    userId: 1,
    spreadId: 2,
    title: "Focus for the month",
    question: "What should I focus on this month?",
    interpretation: "The past leans on old patterns; the present asks for intuition; the future promises renewal if I trust the pull of the moon.",
    cards: [
      { id: 1, tarotCardId: 10, position: "Past", isReversed: false, note: "The hermit's quiet still lingers." },
      { id: 2, tarotCardId: 19, position: "Present", isReversed: false, note: "Trust what the shadows show." },
      { id: 3, tarotCardId: 18, position: "Future", isReversed: false, note: "A star is waiting." },
    ],
    createdAt: "2026-06-10",
    updatedAt: "2026-06-10",
  },
  {
    id: 26,
    userId: 1,
    spreadId: 1,
    title: "Morning card",
    question: "What do I need to know today?",
    interpretation: "The Sun rises within — say yes to joy.",
    cards: [{ id: 4, tarotCardId: 20, position: "Message", isReversed: false, note: "Bright, wide-awake energy." }],
    createdAt: "2026-07-01",
    updatedAt: "2026-07-01",
  },
];

export const MOCK_FAVORITES: FavoriteCard[] = [
  { id: 1, userId: 1, tarotCardId: 19, createdAt: "2026-05-02" },
  { id: 2, userId: 1, tarotCardId: 18, createdAt: "2026-05-14" },
  { id: 3, userId: 1, tarotCardId: 3, createdAt: "2026-06-20" },
];
