/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ReadingsRouteImport } from './routes/readings'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as SpreadsRouteImport } from './routes/spreads'
import { Route as LibraryIdRouteImport } from './routes/library.$id'
import { Route as ReadingsIdRouteImport } from './routes/readings.$id'
import { Route as ReadingsNewRouteImport } from './routes/readings.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadingsRoute = ReadingsRouteImport.update({
  id: '/readings',
  path: '/readings',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const SpreadsRoute = SpreadsRouteImport.update({
  id: '/spreads',
  path: '/spreads',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryIdRoute = LibraryIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => LibraryRoute,
} as any)
const ReadingsIdRoute = ReadingsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ReadingsRoute,
} as any)
const ReadingsNewRoute = ReadingsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ReadingsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/favorites': typeof FavoritesRoute
  '/library': typeof LibraryRouteWithChildren
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/readings': typeof ReadingsRouteWithChildren
  '/register': typeof RegisterRoute
  '/spreads': typeof SpreadsRoute
  '/library/$id': typeof LibraryIdRoute
  '/readings/$id': typeof ReadingsIdRoute
  '/readings/new': typeof ReadingsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/favorites': typeof FavoritesRoute
  '/library': typeof LibraryRouteWithChildren
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/readings': typeof ReadingsRouteWithChildren
  '/register': typeof RegisterRoute
  '/spreads': typeof SpreadsRoute
  '/library/$id': typeof LibraryIdRoute
  '/readings/$id': typeof ReadingsIdRoute
  '/readings/new': typeof ReadingsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/favorites': typeof FavoritesRoute
  '/library': typeof LibraryRouteWithChildren
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/readings': typeof ReadingsRouteWithChildren
  '/register': typeof RegisterRoute
  '/spreads': typeof SpreadsRoute
  '/library/$id': typeof LibraryIdRoute
  '/readings/$id': typeof ReadingsIdRoute
  '/readings/new': typeof ReadingsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/favorites'
    | '/library'
    | '/login'
    | '/profile'
    | '/readings'
    | '/register'
    | '/spreads'
    | '/library/$id'
    | '/readings/$id'
    | '/readings/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/favorites'
    | '/library'
    | '/login'
    | '/profile'
    | '/readings'
    | '/register'
    | '/spreads'
    | '/library/$id'
    | '/readings/$id'
    | '/readings/new'
  id:
    | '__root__'
    | '/'
    | '/favorites'
    | '/library'
    | '/login'
    | '/profile'
    | '/readings'
    | '/register'
    | '/spreads'
    | '/library/$id'
    | '/readings/$id'
    | '/readings/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FavoritesRoute: typeof FavoritesRoute
  LibraryRoute: typeof LibraryRouteWithChildren
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  ReadingsRoute: typeof ReadingsRouteWithChildren
  RegisterRoute: typeof RegisterRoute
  SpreadsRoute: typeof SpreadsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/readings': {
      id: '/readings'
      path: '/readings'
      fullPath: '/readings'
      preLoaderRoute: typeof ReadingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spreads': {
      id: '/spreads'
      path: '/spreads'
      fullPath: '/spreads'
      preLoaderRoute: typeof SpreadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/$id': {
      id: '/library/$id'
      path: '/$id'
      fullPath: '/library/$id'
      preLoaderRoute: typeof LibraryIdRouteImport
      parentRoute: typeof LibraryRoute
    }
    '/readings/$id': {
      id: '/readings/$id'
      path: '/$id'
      fullPath: '/readings/$id'
      preLoaderRoute: typeof ReadingsIdRouteImport
      parentRoute: typeof ReadingsRoute
    }
    '/readings/new': {
      id: '/readings/new'
      path: '/new'
      fullPath: '/readings/new'
      preLoaderRoute: typeof ReadingsNewRouteImport
      parentRoute: typeof ReadingsRoute
    }
  }
}

interface LibraryRouteChildren {
  LibraryIdRoute: typeof LibraryIdRoute
}

const LibraryRouteChildren: LibraryRouteChildren = {
  LibraryIdRoute: LibraryIdRoute,
}

const LibraryRouteWithChildren =
  LibraryRoute._addFileChildren(LibraryRouteChildren)

interface ReadingsRouteChildren {
  ReadingsIdRoute: typeof ReadingsIdRoute
  ReadingsNewRoute: typeof ReadingsNewRoute
}

const ReadingsRouteChildren: ReadingsRouteChildren = {
  ReadingsIdRoute: ReadingsIdRoute,
  ReadingsNewRoute: ReadingsNewRoute,
}

const ReadingsRouteWithChildren = ReadingsRoute._addFileChildren(
  ReadingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FavoritesRoute: FavoritesRoute,
  LibraryRoute: LibraryRouteWithChildren,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  ReadingsRoute: ReadingsRouteWithChildren,
  RegisterRoute: RegisterRoute,
  SpreadsRoute: SpreadsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
